### ISSUE TITLE
User requirements

### ISSUE THREAD

**Issue by NouraldinS** [NoureldeanSaed/team-lead-assignment#1]
As a user I expect to have the following functionalities:
---
- [ ] User's accounts
  - [ ] User login #2 
  - [ ] User signup #3 
  - [ ] User profile #4 
  - [ ] User password-reset #5 
  - [ ] User account-settings #6 
---
- [ ] Dashboard
  - [ ] Show relevant video options for the user #7 
  - [ ] Show a resumable video page #8
